project_id = "zjavhxzlbcgqvqegipmv"

[functions.paystack-webhook]
verify_jwt = false

[functions.flutterwave-webhook]
verify_jwt = false

[functions.youtube-live-status]
verify_jwt = false

[functions.submit-partnership-inquiry]
verify_jwt = false
